ALT_BT_DEBUT="Aller au premier coup";
ALT_BT_RECULE="Coup précédent";
ALT_BT_PAUSE="Pause";
ALT_BT_AVANCE="Coup suivant";
ALT_BT_FIN="Aller au dernier coup";
ALT_BT_STOP="Quitter";

BT_ANNUL="Annuler";
BT_ACCEPTE="Accepter et jouer";
BT_DP="Démarrer la partie";
BT_MAIN="Jouer à la main";
BT_PEC="Partie en un clic";
BT_PPP="Partie pas à pas";
BT_REFUSER_SANS="Refuser net";
BT_REFUSER_AVEC="Refuser en commentant";
BT_VALIDER="Valider";

CNX_1="Quel pseudo ?";
CNX_2="Quel mot de passe ?";
CNX_3="Mots de passes différents !";
CNX_4="Patience ...";
CNX_5="Quel nom ?";
CNX_6="Quel prénom ?";
//CNX_7="Merci, du fait de congés, ces informations seront prises en compte lundi 31 décembre.\n\nEn attendant, inscrivez-vous en tant que Public Programmers.\n\nAinsi votre mail sera renseigné, et nous vous préviendrons par ce biais.\nNB:L'adresse mail ne sera jamais utilisée à d'autres fins que ce type d'échanges.";
CNX_7="Merci, ces informations devraient être prises en compte d'ici demain au plus tard.\n\nEn attendant, inscrivez-vous en tant que Public Programmers.\n\nAinsi votre mail sera renseigné, et nous vous préviendrons par ce biais.\nNB:L'adresse mail ne sera jamais utilisée à d'autres fins que ce type d'échanges.";
CNX_8="Quel pays ?";
CNX_9="Quelle école ?";
CNX_10="Quel mail ?";
CNX_11="Quelle année ?";
CNX_12="Quelle URL ?";
CNX_13="Quel domaine mail ?";

CONSOLE_CONSIGNE="A vous de jouer";
CONSOLE_ENREGISTRER="Enregistrer";
CONSOLE_PLUSTARD="Continuer plus tard";
CONSOLE_PHOTO="Photographier";
CONSOLE_REGLE="Règle du jeu";
CONSOLE_QUIT="Quitter le plateau";
CONSOLE_TRACEURL="Voir les URL";

CONTACT_1="Où est le message ?"; //cette série est utilisée aussi dans reaction.php
CONTACT_2="Veuillez patienter";
CONTACT_3="Merci pour le message !";

MOT_A="à"; //exemple : gain 10 à 5
MOT_ABANDONNER="Abandonner";
MOT_ANNULER="Annuler";
MOT_ATTENTE="Chargement ...";
MOT_AVEC_PHOTO="Avec la photo";
MOT_CHEMIN="Quel chemin ?";
MOT_COUP="Coup";
MOT_CPSUIV="Coup suivant";
MOT_DESOLE="Désolé,";
MOT_ENREG="Enregistrer";
MOT_ETAPE="Etape";
MOT_FERMER="Fermer";
MOT_JEU="Quel jeu ?";
MOT_MODIFIER="Modifier";
MOT_NEW="Nouvelle partie";
MOT_PLATEAU="Avec quel plateau ?";
MOT_PROPS="Les <b>propriétés</b>";
MOT_RENOM="Nouveau nom ?";
MOT_RETOUR="Retour";
MOT_REVOIR="Revoir";
MOT_SAISIE='Saisie vide ou trop courte (moins de 4 caractères)';
MOT_SECONDES="sec."
MOT_URL="Quelle URL ?"
MOT_VALIDER="Valider"
MOT_VOUS="Toi"

REVERSI_BLANCS_PASSENT='Les blancs passent'
REVERSI_JEPASSE='Je passe'
REVERSI_NOIRS_PASSENT='Les noirs passent'

TXT_AUTO="AUTO";
TXT_BAD_ID="Ce n'est pas l'identifiant enregistré ...";
TXT_BAD_ICONE="Ce n'est pas un '.gif' ...";
TXT_BRAVO="Bravo, tu gagnes par";
TXT_BRAVO2="Bravo, tu as gagné";
TXT_CREAJEU="Etes-vous sûr de vouloir supprimer ce jeu ?";
TXT_CREAJEU2="Avec quel identifiant ?";
TXT_COMPET="On n'est pas autorisé à voter pour soi-même ...";
TXT_COMPET2="Dernières parties jouéees par ";
TXT_DEFI="Es-tu sûr de vouloir supprimer ce défi ?"
TXT_DEFI2="Parties jouéees contre ";
TXT_ECHANGE="Débogage : Echanges d'URL entre ton code et Tournoyons";
TXT_EGALITE="Egalité !";
TXT_ENREG="Saisissez le titre donné à cette partie (pour la retrouver dans les parties enregistrées).";
TXT_ENREG_ENCOURS="Saisissez le titre donné à cette partie (pour la retrouver dans les parties en cours) et\n à la photo du dernier coup (pour la retrouver dans 'nouvelle partie').";
TXT_ENREG_ENCOURS2="La partie est disponible pour être revue (menu 'parties en cours'), ou pour repartir de là (photo  dans 'nouvelle partie')";
TXT_ENREG_ENREG="La partie est disponible (menu 'parties enregistrées')";
TXT_ERREUR1="coup invalide de valeur ";
TXT_ERREUR2="coup de valeur invalide";
TXT_ERREUR_MOTEUR="Erreur du moteur - ";
TXT_ERRNUM="ce n'est pas un nombre valide !";
TXT_FICHE="Fiche de ";
TXT_GAGNE="a gagné par";
TXT_GAGNE2="a gagné";
TXT_INSCRIPTION="En tant que 'Public Programmers', vous pouvez uniquement inscrire des moteurs de jeu.";
TXT_INVITE1="Tu veux inviter";
TXT_INVITE2="à jouer à";
TXT_INVITE3="Nous te proposons d'attendre<BR>la réponse de";
TXT_INVITE4="à ton invitation<BR> à jouer à";
TXT_INVITE5="avec toi ...";
TXT_INVITE6="L'invitation est transmise, attendons ...";
TXT_INVITE7="Ton partenaire est prévenu de cet abandon.";
TXT_INVITE8="Hey, ton partenaire a abandonné la partie ...";
TXT_INTROUVABLE="n'existe pas ou n'est pas accessible (erreur HTTP). Cherche le souci et réessaye le bouton Valider."
TXT_JS="Après OK, faire clic-droit > Ce cadre > Actualiser le cadre (ou équivalent de votre navigateur)\n pour mettre à niveau certains fichiers de cette partie du site en frame";
TXT_LANCER="Surveiller la liste des connectés acceptant les invitations à jouer";
TXT_LANCERb="Dans cette page uniquement";
TXT_LANCERc="Egalement par alerte popup";
TXT_LANCER_S="Surveillance de la liste des connectés acceptant les invitations à jouer<BR>active dans cette page ";
TXT_LANCER_Sb="Surveillance de la liste des connectés acceptant les invitations à jouer active<BR>avec alerte popup de votre navigateur";
TXT_LANCER_Sc="En attendant, vous pouvez faire tout autre chose via votre navigateur ...";
TXT_LANCER_Invite="Invitation transmise - attente réponse ...";
TXT_MANUEL="avance auto";
TXT_MATCH_NUL="Match nul !";
TXT_MASTERMIND="Constituez le code à trouver puis cliquez sur OK";
TXT_NAVALE="Placez-vos bateaux puis Validez, ou ";
TXT_NBCoups=" coups enregistrés.";
TXT_Organise="Trop d'écoles sont sélectionnées ...";
TXT_ORGANISE2="Etes-vous sûr de vouloir supprimer cette compétition ?";
TXT_PERDU="Votre adversaire gagne par";
TXT_PERDU2="Votre adversaire a gagné";
TXT_PHOTO="Saisissez le titre donné à cette photo (pour la retrouver).";
TXT_PHOTO2="en partant d'une photo de jeu";
TXT_PHOTO3="La photo est disponible (menu 'nouvelle partie')";
TXT_PHOTO_CONTEXTE="Le contexte de jeu (voir manuel technique pour la syntaxe) de cette photo est :";
TXT_POKER1="Veuillez miser";
TXT_PREMIER="Le premier joueur";
TXT_REGISTER="Es-tu sûr de  vouloir supprimer ";
TXT_REGISTER_INTERFACE="cette interface";
TXT_REGISTER_MOTEUR="ce moteur";
TXT_REINVITE="Inviter votre partenaire à jouer une nouvelle partie ?";
TXT_REFUS_NET="Invitation refusée ...";
TXT_REVOIR="Revoir pas à pas";
TXT_SINSCRIRE="Super ! Tu es inscrit à la compétition. Bonne chance à toi ...";
TXT_SECOND="Le second joueur";
TXT_STRATEGIE="Etes-vous sûrs de vouloir supprimer cette réaction ?";
TXT_SUIV="Cliquer sur votre choix";
TXT_SUIV2="Cliquer sur la case disponible de votre choix";
TXT_TESTEUR="Passer l'URL du fichier interface à tester en querystring : '?URL='";
TXT_TESTEUR2="Fonctionne uniquement en local (serveur='localhost')";
TXT_WEBMASTER="Vous êtes sûrs de vouloir supprimer cet utilisateur ?";

MESSNAVTOUCHE='Touché !';
MESSNAVCOULE='Coulé !';
